### ISSUE TITLE
How to scan file from the system

### ISSUE THREAD

**Issue by mosinconsrv** [michael79bxl/cordova-barcode-scanner-plugin2#1]
Hi there,
I am developing a ionic mobile app in which I need to read a qr code image from the system.
Your plugin allows to scan a image using device camera but instead I need to scan a image file from within the device.

Regards,
Kuljeet

**Comment by michael79bxl** [comment]
Hi,

You could use a full javascript code instead. This one is working properly.

https://github.com/LazarSoft/jsqrcode <https://github.com/LazarSoft/jsqrcode>

Regards,

Michael
