### ISSUE TITLE
Viewfinder image is inverted on Nexus 5x

### ISSUE THREAD

**Issue by rogerhyam** [michael79bxl/cordova-barcode-scanner-plugin2#2]
Hi,

Thanks for writing this plugin. I'm enjoying playing with it and it will be really useful in production.

I have one issue though. I just got a shiny new Nexus 5x and the viewfinder image is inverted. I think this is a common issue and there is a fix described here:

https://code.google.com/p/android/issues/detail?id=191210

I'd rather not dig into the Android code if I can avoid it. Maybe you could fix it easily?

Many thanks,

Roger

p.s. The 5x is really quite nice - if a bit plastic

**Comment by michael79bxl** [comment]
Sorry, this plugin will not be updated for a specific model.

**Comment by rogerhyam** [comment]
If you read the issues on 191210 on the Android forum it is that the camera orientation isn't being checked correctly. Although this is currently only a *known* issue with the 5X there is nothing to stop it happening with other phones and as you will never know which phones they are you will never know that it is happening - until someone mentions it. It is a minor fix to make sure the API is called correctly on all devices. The Nexus series are also thought of as reference devices for Android implementations so it is kind of nice to have it working on them.

Maybe further down the line I'll take a look at it myself.

Thanks,

Roger
