### ISSUE TITLE
Visual Studios 2015 compatability

### ISSUE THREAD

**Issue by Ledbelly2142** [michael79bxl/cordova-barcode-scanner-plugin2#3]
Hi, looks like a great plugin and I would really like to use it in Visual Studios 2015. When attempting to add the plugin, I get the error: 
Visual Studios was unable to parse plugin.xml. Please ensure plugin.xml exists and contains no errors.  

I can load other plugins from a git repo, so I am pretty sure VS works loading git files. After looking at troubleshooting potential issues, it looks like there may be some things that Visual Studios 2015 requires that are not included in the plugin.xml file. I am willing to attempt to make it work, but am not sure how to make it compatible. Any pointers on where to start?

Thanks

**Comment by michael79bxl** [comment]
This version of the plugin is android only.
(README and version updated).

**Comment by Ledbelly2142** [comment]
Ok, thanks.
